"""init db.

Revision ID: 4af1d594909f
Revises:
Create Date: 2025-07-21 23:05:58.397626

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4af1d594909f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parameter_sweep_configs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Array of parameter objects with key, type, and values",
        ),
        sa.Column(
            "parameter_count",
            sa.Integer(),
            nullable=False,
            comment="Number of parameters in this configuration",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_parameters_gin",
        "parameter_sweep_configs",
        ["parameters"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_parameter_sweep_configs_created_at"),
        "parameter_sweep_configs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_parameter_sweep_configs_name"), "parameter_sweep_configs", ["name"], unique=False
    )
    op.create_table(
        "simulation_status",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("config_id", sa.UUID(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False, comment="Progress from 0 to 100"),
        sa.Column(
            "state",
            sa.String(length=20),
            nullable=False,
            comment="QUEUED | RUNNING | COMPLETED | FAILED",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_config_id_created_at", "simulation_status", ["config_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_config_id_created_at", table_name="simulation_status")
    op.drop_table("simulation_status")
    op.drop_index(op.f("ix_parameter_sweep_configs_name"), table_name="parameter_sweep_configs")
    op.drop_index(
        op.f("ix_parameter_sweep_configs_created_at"), table_name="parameter_sweep_configs"
    )
    op.drop_index(
        "idx_parameters_gin", table_name="parameter_sweep_configs", postgresql_using="gin"
    )
    op.drop_table("parameter_sweep_configs")
    # ### end Alembic commands ###
